In [53]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
# Load Dataset
df = pd.read_csv("luxury_cosmetics_fraud_analysis_2025.csv")
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Time,Customer_Age,Customer_Loyalty_Tier,Location,Store_ID,Product_SKU,Product_Category,Purchase_Amount,Payment_Method,Device_Type,IP_Address,Fraud_Flag,Footfall_Count
0,702bdd9b-9c93-41e3-9dbb-a849b2422080,119dca0b-8554-4b2d-9bec-e964eaf6af97,2025-07-27,04:04:15,56.0,Silver,San Francisco,FLAGSHIP-LA,NEBULA-SERUM-07,Concealer,158.24,Mobile Payment,Desktop,239.249.58.237,0,333
1,2e64c346-36bc-4acf-bc2b-8b0fdf46abc5,299df086-26c4-4708-b6d7-fcaeceb14637,2025-03-14,20:23:23,46.0,Platinum,Zurich,BOUTIQUE-SHANGHAI,STELLAR-FOUND-03,Lipstick,86.03,Credit Card,Tablet,84.49.227.90,0,406
2,29ad1278-70ce-421f-8d81-23816b39f4ac,dfa3d24d-b935-49a5-aa1d-7d57a44d8773,2025-02-20,12:36:02,32.0,Silver,Milan,POPUP-TOKYO,SOLAR-BLUSH-04,Mascara,255.69,Gift Card,Desktop,79.207.35.55,0,96
3,07dc4894-e0eb-48f1-99a7-1942b1973d9b,7a67e184-9369-49ee-aeac-18f5b51b230f,2025-04-25,19:09:43,60.0,Bronze,London,BOUTIQUE-NYC,GALAXIA-SET-08,Serum,282.76,Gift Card,Mobile,176.194.167.253,0,186
4,ae407054-5543-429c-918a-cdcc42ea9782,cf14730a-8f5a-453d-b527-39a278852b27,2025-04-17,14:23:23,NaN,Platinum,Miami,BOUTIQUE-NYC,LUNAR-MASC-02,Serum,205.86,Gift Card,Mobile,166.31.46.111,0,179

In [55]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Time',
       'Customer_Age', 'Customer_Loyalty_Tier', 'Location', 'Store_ID',
       'Product_SKU', 'Product_Category', 'Purchase_Amount', 'Payment_Method',
       'Device_Type', 'IP_Address', 'Fraud_Flag', 'Footfall_Count'],
      dtype='object')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         2133 non-null   object
 1   Customer_ID            2133 non-null   object
 2   Transaction_Date       2133 non-null   object
 3   Transaction_Time       2133 non-null   object
 4   Customer_Age           2027 non-null   float64
 5   Customer_Loyalty_Tier  2027 non-null   object
 6   Location               2133 non-null   object
 7   Store_ID               2133 non-null   object
 8   Product_SKU            2133 non-null   object
 9   Product_Category       2133 non-null   object
 10  Purchase_Amount        2133 non-null   float64
 11  Payment_Method         2027 non-null   object
 12  Device_Type            2133 non-null   object
 13  IP_Address             2133 non-null   object
 14  Fraud_Flag             2133 non-null   int64
 15  Footfall_Count         2133 non-null   int64
dtypes: float64(2), int64(2), object(12)
memory usage: 266.8+ KB

In [57]:
df.describe()

       Customer_Age  Purchase_Amount   Fraud_Flag  Footfall_Count
count   2027.000000      2133.000000  2133.000000     2133.000000
mean      41.684262       174.614074     0.030942      272.461791
std       13.718110        72.249043     0.173202      131.113027
min       18.000000        50.260000     0.000000       50.000000
25%       30.000000       113.850000     0.000000      157.000000
50%       42.000000       174.180000     0.000000      269.000000
75%       53.000000       236.360000     0.000000      388.000000
max       65.000000       299.910000     1.000000      500.000000

In [58]:
df.isnull().sum()

Transaction_ID             0
Customer_ID                0
Transaction_Date           0
Transaction_Time           0
Customer_Age             106
Customer_Loyalty_Tier    106
Location                   0
Store_ID                   0
Product_SKU                0
Product_Category           0
Purchase_Amount            0
Payment_Method           106
Device_Type                0
IP_Address                 0
Fraud_Flag                 0
Footfall_Count             0
dtype: int64

In [59]:
# Handelling Missing Values

df["Customer_Age"].fillna(df["Customer_Age"].mean(),  inplace = True )
df["Customer_Loyalty_Tier"].fillna("Other", inplace=True)
df["Payment_Method"].fillna("Other", inplace=True)

C:\Users\waghv\AppData\Local\Temp\ipykernel_109404\498814429.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Customer_Age"].fillna(df["Customer_Age"].mean(),  inplace = True )
C:\Users\waghv\AppData\Local\Temp\ipykernel_109404\498814429.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Customer_Loyalty_Tier"].fillna("Other", inplace=True)
C:\Users\waghv\AppData\Local\Temp\ipykernel_109404\498814429.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Payment_Method"].fillna("Other", inplace=True)

In [60]:
df.isnull().sum()

Transaction_ID           0
Customer_ID              0
Transaction_Date         0
Transaction_Time         0
Customer_Age             0
Customer_Loyalty_Tier    0
Location                 0
Store_ID                 0
Product_SKU              0
Product_Category         0
Purchase_Amount          0
Payment_Method           0
Device_Type              0
IP_Address               0
Fraud_Flag               0
Footfall_Count           0
dtype: int64

In [61]:
# Change datatypes

df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])
df["Transaction_Time"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.time
df["Customer_Age"] = df["Customer_Age"].astype(int)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         2133 non-null   object
 1   Customer_ID            2133 non-null   object
 2   Transaction_Date       2133 non-null   datetime64[ns]
 3   Transaction_Time       2133 non-null   object
 4   Customer_Age           2133 non-null   int32
 5   Customer_Loyalty_Tier  2133 non-null   object
 6   Location               2133 non-null   object
 7   Store_ID               2133 non-null   object
 8   Product_SKU            2133 non-null   object
 9   Product_Category       2133 non-null   object
 10  Purchase_Amount        2133 non-null   float64
 11  Payment_Method         2133 non-null   object
 12  Device_Type            2133 non-null   object
 13  IP_Address             2133 non-null   object
 14  Fraud_Flag             2133 non-null   int64
 15  Footfall_Count         2133 non-null   int64
dtypes: datetime64[ns](1), float64(1), int32(1), int64(2), object(11)
memory usage: 258.4+ KB

In [63]:
type(df["Transaction_Time"].iloc[0])

datetime.time

In [64]:
df.duplicated().sum()

0

In [66]:
# Example: Flag high-risk transactions by amount and loyalty tier
df['High_Risk_Transaction'] = np.where((df['Purchase_Amount']>5000) & (df['Customer_Loyalty_Tier']=='Bronze'), 1, 0)

In [76]:
df.to_csv("New Clean Data.csv")